// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class 1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 1() {
    driver.get("https://devexpress.github.io/testcafe/example/");
    driver.manage().window().setSize(new Dimension(1050, 811));
    driver.findElement(By.id("developer-name")).click();
    driver.findElement(By.id("developer-name")).sendKeys("Alex");
    driver.findElement(By.id("populate")).click();
    assertThat(driver.switchTo().alert().getText(), is("Reset information before proceeding?"));
    driver.switchTo().alert().dismiss();
    driver.findElement(By.cssSelector("fieldset:nth-child(2) > p:nth-child(2) > label")).click();
    driver.findElement(By.id("tried-test-cafe")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ui-slider-handle"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ui-slider-handle"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ui-slider-handle"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("slider")).click();
    driver.findElement(By.id("comments")).click();
    driver.findElement(By.cssSelector("fieldset:nth-child(1) > p:nth-child(2) > label")).click();
    driver.findElement(By.id("preferred-interface")).click();
    {
      WebElement dropdown = driver.findElement(By.id("preferred-interface"));
      dropdown.findElement(By.xpath("//option[. = 'JavaScript API']")).click();
    }
    driver.findElement(By.id("submit-button")).click();
    driver.findElement(By.cssSelector("body")).click();
  }
}
